### ISSUE TITLE
Less than signs < without closing greater than signs > get highlighted as automatic links.

### ISSUE THREAD

**Issue by cirosantilli** [preservim/vim-markdown#104]
Example: `1 < 2`

`<` cannot be escaped with `\`: http://daringfireball.net/projects/markdown/syntax#autolink

If there is no closing `>` on the same line it should not get highlighted.

Extracted from: https://github.com/plasticboy/vim-markdown/issues/49

**Comment by paldepind** [comment]
This issue seems to have popped up again. I'm using vim-markdown and a single `<` on a line breaks the syntax highlighting as can be seen in the image below.

![image](https://user-images.githubusercontent.com/521604/37564885-18e7707c-2a9f-11e8-9298-6d66cdef7da5.png)
