### ISSUE TITLE
Way to disable auto indentation for making list

### ISSUE THREAD

**Issue by yous** [preservim/vim-markdown#109]
```
- A<cursor>
```

Press `<Enter>`

What I expected:

```
- A
<cursor>
```

But I get:

```
- A
    <cursor>
```

I just want to add items to list without pressing backspace repeatedly. Is there any option to disable this auto indentation or any trigger to dedent the line? Just typing `-` makes a nested list.

**Comment by raheelahmad** [comment]
I had Syntactic with `let g:syntastic_auto_loc_list = 1` which was chasing the same issue.
