### ISSUE TITLE
syntax error with special url link

### ISSUE THREAD

**Issue by ZSaberLv0** [preservim/vim-markdown#351]
```markdown
abc [http://www.xxx.com](http://www.xxx.com) def

xyz
```

expected result: only the links highlighted

current wrong result: `def` and `xyz` would also be highlighted

**Comment by codevbus** [comment]
I am currently seeing this as well. All plaintext after the link is highlighted/underlined with the exception of headers and code blocks.

**Comment by lggruspe** [comment]
This seems to have been fixed by #451.
