### ISSUE TITLE
syntax for code blocks disappears when enter insert mode

### ISSUE THREAD

**Issue by Adnios** [preservim/vim-markdown#575]
![syntax](https://user-images.githubusercontent.com/41060790/158045167-522fd9af-0a83-4cfe-b2ec-eb65ffb73867.gif)
As the gif file shown:
1. enter insert mode.
  a. syntax for code block disappear
2. now I type :e<CR>
  a. syntax works

**Comment by alerque** [comment]
Did you resolve this or why was it closed?
