### ISSUE TITLE
About sysntax highlighting

### ISSUE THREAD

**Issue by blueair5** [preservim/vim-markdown#581]
sorry ! When  I create a file on  a Linux server with a .md suffix, and edit this file ,there is no markdown syntax highlighting. 😢 .
But when I open a README.md , there is highlighting.  I don't know why ? 
My English is not good, sorry!

**Comment by alerque** [comment]
When you edit one of your other files that is not getting highlighting, what is the active filetype? (Find out with `:set filetype`).

**Comment by blueair5** [comment]
when I use :set filetype , result is filetype=modula2

**Comment by blueair5** [comment]
> When you edit one of your other files that is not getting highlighting, what is the active filetype? (Find out with `:set filetype`).
The result is filetype=modula2

**Comment by blueair5** [comment]
> When you edit one of your other files that is not getting highlighting, what is the active filetype? (Find out with `:set filetype`).

Thanks for your reminder, I found  a tutorial to solve this problem,thank you so much!

**Comment by blueair5** [comment]
This is a Chinese tutorial，https://qa.1r1g.com/sf/ask/1629550471/?lastactivity
