### ISSUE TITLE
Toc not working w/ lua config

### ISSUE THREAD

**Issue by rodhash** [preservim/vim-markdown#584]
Hello,

Recently migrated my config to nvim/lua and apparently I can't properly use Toc now.

When using just nvim with vimrc config files it all works fine but when I switch to my lua config, it kinda works, it is able to open Toc but fails when I try to navigate to any MD title.

When I press Enter it only expands the Toc size instead of moving to the title.

https://user-images.githubusercontent.com/29671981/169875187-786f81f8-489d-4b65-814e-572f323fe519.mp4

**Comment by rodhash** [comment]
Well I'm not sure what exactly happened but after reinstalling it's back to normal, I'm now able to use this sweet TOC that I enjoy so much and couldn't find anything similar in the lua world!

**Comment by alerque** [comment]
What plugin manager were you using from VimL and what plugin manager did you use from Lua? If there is something we can replicate here I'd be happy to look into it.

**Comment by rodhash** [comment]
Hi, it was Plug/vimL and Packer/lua

**Comment by alerque** [comment]
And does it now work with Packer again or are you back to vim-plug?

**Comment by alerque** [comment]
Thanks for reporting back.

I don't think the speed is going to be a problem with this plugin, we get loaded the same way and run in the same language either way. I'm not even sure we could detect the difference is what loaded us if we wanted to. You likely have something else going on one side of your setup causing the difference.

**Comment by rodhash** [comment]
Yeah agree probably something else is messing up with the performance on MD files and I need to dig a bit more on it, I couldn't find the root cause yet but I noticed that somelse else kicks in alongside the syntax highlighting .. disabling the syntax highlighting things get back to normal.

Another plugin having different behaviour is the vim-floaterm, apparently it messes up my mkview/loadview setting. But alright my Lua migration is basically done with couple minor issues that I need to work on.

Regarding the performance aspect I don't see any difference between both setup, honestly I expected to see some difference based on what I read around. Not even in my work laptop which has less CPU power I don't see much gain.

Anyway really appreciate your help / attention, take care bud!
