### ISSUE TITLE
[Function request] How to make the text stay unfold when the cursor moves to another place.

### ISSUE THREAD

**Issue by draftman9** [preservim/vim-markdown#590]
The md text was folded first of all. When I open a text area and move the cursor out of it, the text area was auto folded which is not my expectation. Could you please tell me how to modify it for this plugin or Is there any chance to fix it? 😄

**Comment by amacfie** [comment]
Try
```vim
let g:vim_markdown_folding_disabled = 1
let g:markdown_folding = 1
```
