### ISSUE TITLE
Highlight headers

### ISSUE THREAD

**Issue by mcandre** [preservim/vim-markdown#74]
Would be nice if `# ...` headers in markdown files were syntax highlighted like function names in source code files.

**Comment by cup** [comment]
https://github.com/plasticboy/vim-markdown/issues/388
https://github.com/plasticboy/vim-markdown/issues/458
https://github.com/plasticboy/vim-markdown/issues/461
https://github.com/plasticboy/vim-markdown/issues/471

https://github.com/plasticboy/vim-markdown/issues/74
